-- Задача: Посчитать новых пользователей и новых курьеров по дате первого действия + накопительные итоги.
-- Решение использует: CTE, объединение дат (UNION), оконная сумма SUM() OVER (ORDER BY date).
-- Результат: date, new_users, new_couriers, total_users, total_couriers.
-- Примечания: дата первого действия = MIN(time)::date для каждого user/courier.
