-- Задача: Посчитать среднее время доставки по дням (от accept_order до deliver_order).
-- Решение использует: join по order_id, разница времён, EXTRACT(EPOCH), агрегирование AVG().
-- Результат: date, minutes_to_deliver.
-- Примечания: учитываются только заказы, у которых есть событие deliver_order.
