-- Задача: Посчитать по часам: количество доставленных и отменённых заказов + долю отмен (cancel rate).
-- Решение использует: выделение часа из времени заказа, подмножества по статусам, расчёт отношения.
-- Результат: hour, successful_orders, canceled_orders, cancel_rate.
-- Примечания: cancel_rate = canceled / (successful + canceled).
